apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}-deployment
  labels:
    app: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.name }}
    spec:
      containers:
        - name: {{ .Values.metadata.name }}
          image: {{ .Values.image.registry }}/{{ .Values.image.project }}/{{ .Values.image.name }}:{{ .Values.image.tags }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.env.database.url | quote }}
            - name: DATABASE_USER_ID
              value: {{ .Values.env.database.user.id | quote }}
            - name: DATABASE_USER_PASSWORD
              value: {{ .Values.env.database.user.password | quote }}

      imagePullSecrets:
        - name: {{ .Values.image.secret }}
